CREATE DATABASE IF NOT EXISTS test CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER 'tamco'@'%' IDENTIFIED BY '1qazxsw2';

GRANT ALL PRIVILEGES ON test.* TO tamco@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
